### ISSUE TITLE
无法启动最新版本的fluentd-pilot

### ISSUE THREAD

**Issue by hujianxiong** [AliyunContainerService/fluentd-pilot#63]
使用命令 docker run -u root --rm -it     -v /var/run/docker.sock:/var/run/docker.sock     -v /:/host     registry.cn-hangzhou.aliyuncs.com/acs-sample/fluentd-pilot:latest 报错
```
[root@test06.swarm.anget04 webapps]# docker run -u root --rm -it     -v /var/run/docker.sock:/var/run/docker.sock     -v /:/host     registry.cn-hangzhou.aliyuncs.com/acs-sample/fluentd-pilot:latest 
use default output
umount: can't unmount /host/yschome/data/docker/overlay/fdd4462624ebe89972a60b9db231ed1069a90ff3f6f6fcf4cd7934f73f7fb59a/merged: Operation not permitted
Traceback (most recent call last):
  File "/pilot/entrypoint", line 34, in <module>
    cleanup()
  File "/pilot/entrypoint", line 24, in cleanup
    umount(volume)
  File "/pilot/entrypoint", line 12, in umount
    subprocess.check_call('umount %s' % volume, shell=True) 
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'umount /host/yschome/data/docker/overlay/fdd4462624ebe89972a60b9db231ed1069a90ff3f6f6fcf4cd7934f73f7fb59a/merged' returned non-zero exit status 1
```
加上privileged还是报错
```
[root@test06.swarm.anget04 webapps]# docker run --rm -it --privileged  -v /var/run/docker.sock:/var/run/docker.sock   -v /:/host  registry.cn-hangzhou.aliyuncs.com/acs-sample/fluentd-pilot:latest
use default output
umount: can't unmount /host/run: Resource busy
Traceback (most recent call last):
  File "/pilot/entrypoint", line 34, in <module>
    cleanup()
  File "/pilot/entrypoint", line 24, in cleanup
    umount(volume)
  File "/pilot/entrypoint", line 12, in umount
    subprocess.check_call('umount %s' % volume, shell=True) 
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'umount /host/run' returned non-zero exit status 1
```

**Comment by BSWANG** [comment]
用最新的代码构建出镜像就不会存在这个问题了。最新的代码只会umount引起busy问题的shm目录 https://github.com/AliyunContainerService/fluentd-pilot/blob/master/docker-images/entrypoint#L22-L23

**Comment by BSWANG** [comment]
docker run --rm -it --privileged  -v /var/run/docker.sock:/var/run/docker.sock   -v /:/host  registry.cn-hangzhou.aliyuncs.com/acs-sample/fluentd-pilot:0.7.1
这个版本修复了这个问题

**Comment by buhe** [comment]
在 swarm mode 还是会有这个问题：

```
version: "3.3"
services:
  logs:
    image: "registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest"
    volumes:
      - "/:/host"
      - "/var/run/docker.sock:/var/run/docker.sock"
    net: "host"
    privileged: true
    environment:
      - FLUENTD_OUTPUT=aliyun_sls
      - ALIYUNSLS_PROJECT=white-logs
      - ALIYUNSLS_REGION_ENDPOINT=cn-hangzhou.log.aliyuncs.com
      - ALIYUNSLS_ACCESS_KEY_ID=exempwg0U6rl1yL_2G4A_00weNY5kEdMeG7oYH04
      - ALIYUNSLS_ACCESS_KEY_SECRET=8dhh34fcyMD3tDobvwSrsWbhX
      - ALIYUNSLS_CREATE_LOGSTORE_TTL=7 # 7 day
    deploy:
      mode: global
```
